title: The Text
description: > # this means to ignore newlines until "baseurl:"
  for insight, knowledge
permalink: ':title/'
baseurl: "https://qualitytext.github.io" # the subpath of your site, e.g. /blog
url: "https://qualitytext.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "" #if your site has a twitter account, enter it here

# Author Settings
author: The Text # add your name
author-img: Text.png # add your photo
about-author: Every text for inspiration # add description
twitter: # add your Twitter handle
facebook: forthetext # add your Facebook handle
email: ratsgo@naver.com # add your Email address

# Disqus
discus-identifier: qualitytext-github-io # add your discus identifier

# Tracker
analytics: UA-93172815-2 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
